//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DBTicketSystemModel", "FK_Tbl_Kullanicilar_Tbl_Yetkiler", "Tbl_Yetkiler", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcTicSys.Tbl_Yetkiler), "Tbl_Kullanicilar", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcTicSys.Tbl_Kullanicilar), true)]
[assembly: EdmRelationshipAttribute("DBTicketSystemModel", "FK_Tbl_Sikayetler_Tbl_Kullanicilar", "Tbl_Kullanicilar", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcTicSys.Tbl_Kullanicilar), "Tbl_Sikayetler", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcTicSys.Tbl_Sikayetler), true)]
[assembly: EdmRelationshipAttribute("DBTicketSystemModel", "FK_Tbl_Sikayetler_Tbl_Onaylar", "Tbl_Onaylar", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcTicSys.Tbl_Onaylar), "Tbl_Sikayetler", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcTicSys.Tbl_Sikayetler), true)]

#endregion

namespace MvcTicSys
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBTicketSystemEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBTicketSystemEntities object using the connection string found in the 'DBTicketSystemEntities' section of the application configuration file.
        /// </summary>
        public DBTicketSystemEntities() : base("name=DBTicketSystemEntities", "DBTicketSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBTicketSystemEntities object.
        /// </summary>
        public DBTicketSystemEntities(string connectionString) : base(connectionString, "DBTicketSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBTicketSystemEntities object.
        /// </summary>
        public DBTicketSystemEntities(EntityConnection connection) : base(connection, "DBTicketSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tbl_Kullanicilar> Tbl_Kullanicilar
        {
            get
            {
                if ((_Tbl_Kullanicilar == null))
                {
                    _Tbl_Kullanicilar = base.CreateObjectSet<Tbl_Kullanicilar>("Tbl_Kullanicilar");
                }
                return _Tbl_Kullanicilar;
            }
        }
        private ObjectSet<Tbl_Kullanicilar> _Tbl_Kullanicilar;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tbl_Onaylar> Tbl_Onaylar
        {
            get
            {
                if ((_Tbl_Onaylar == null))
                {
                    _Tbl_Onaylar = base.CreateObjectSet<Tbl_Onaylar>("Tbl_Onaylar");
                }
                return _Tbl_Onaylar;
            }
        }
        private ObjectSet<Tbl_Onaylar> _Tbl_Onaylar;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tbl_Sikayetler> Tbl_Sikayetler
        {
            get
            {
                if ((_Tbl_Sikayetler == null))
                {
                    _Tbl_Sikayetler = base.CreateObjectSet<Tbl_Sikayetler>("Tbl_Sikayetler");
                }
                return _Tbl_Sikayetler;
            }
        }
        private ObjectSet<Tbl_Sikayetler> _Tbl_Sikayetler;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tbl_Yetkiler> Tbl_Yetkiler
        {
            get
            {
                if ((_Tbl_Yetkiler == null))
                {
                    _Tbl_Yetkiler = base.CreateObjectSet<Tbl_Yetkiler>("Tbl_Yetkiler");
                }
                return _Tbl_Yetkiler;
            }
        }
        private ObjectSet<Tbl_Yetkiler> _Tbl_Yetkiler;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tbl_Kullanicilar EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTbl_Kullanicilar(Tbl_Kullanicilar tbl_Kullanicilar)
        {
            base.AddObject("Tbl_Kullanicilar", tbl_Kullanicilar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tbl_Onaylar EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTbl_Onaylar(Tbl_Onaylar tbl_Onaylar)
        {
            base.AddObject("Tbl_Onaylar", tbl_Onaylar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tbl_Sikayetler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTbl_Sikayetler(Tbl_Sikayetler tbl_Sikayetler)
        {
            base.AddObject("Tbl_Sikayetler", tbl_Sikayetler);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tbl_Yetkiler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTbl_Yetkiler(Tbl_Yetkiler tbl_Yetkiler)
        {
            base.AddObject("Tbl_Yetkiler", tbl_Yetkiler);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBTicketSystemModel", Name="Tbl_Kullanicilar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tbl_Kullanicilar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tbl_Kullanicilar object.
        /// </summary>
        /// <param name="kullaniciID">Initial value of the KullaniciID property.</param>
        public static Tbl_Kullanicilar CreateTbl_Kullanicilar(global::System.Int32 kullaniciID)
        {
            Tbl_Kullanicilar tbl_Kullanicilar = new Tbl_Kullanicilar();
            tbl_Kullanicilar.KullaniciID = kullaniciID;
            return tbl_Kullanicilar;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KullaniciID
        {
            get
            {
                return _KullaniciID;
            }
            set
            {
                if (_KullaniciID != value)
                {
                    OnKullaniciIDChanging(value);
                    ReportPropertyChanging("KullaniciID");
                    _KullaniciID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KullaniciID");
                    OnKullaniciIDChanged();
                }
            }
        }
        private global::System.Int32 _KullaniciID;
        partial void OnKullaniciIDChanging(global::System.Int32 value);
        partial void OnKullaniciIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> YetkiID
        {
            get
            {
                return _YetkiID;
            }
            set
            {
                OnYetkiIDChanging(value);
                ReportPropertyChanging("YetkiID");
                _YetkiID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YetkiID");
                OnYetkiIDChanged();
            }
        }
        private Nullable<global::System.Int32> _YetkiID;
        partial void OnYetkiIDChanging(Nullable<global::System.Int32> value);
        partial void OnYetkiIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KullaniciAdi
        {
            get
            {
                return _KullaniciAdi;
            }
            set
            {
                OnKullaniciAdiChanging(value);
                ReportPropertyChanging("KullaniciAdi");
                _KullaniciAdi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KullaniciAdi");
                OnKullaniciAdiChanged();
            }
        }
        private global::System.String _KullaniciAdi;
        partial void OnKullaniciAdiChanging(global::System.String value);
        partial void OnKullaniciAdiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sifre
        {
            get
            {
                return _Sifre;
            }
            set
            {
                OnSifreChanging(value);
                ReportPropertyChanging("Sifre");
                _Sifre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sifre");
                OnSifreChanged();
            }
        }
        private global::System.String _Sifre;
        partial void OnSifreChanging(global::System.String value);
        partial void OnSifreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Isim
        {
            get
            {
                return _Isim;
            }
            set
            {
                OnIsimChanging(value);
                ReportPropertyChanging("Isim");
                _Isim = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Isim");
                OnIsimChanged();
            }
        }
        private global::System.String _Isim;
        partial void OnIsimChanging(global::System.String value);
        partial void OnIsimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Soyadi
        {
            get
            {
                return _Soyadi;
            }
            set
            {
                OnSoyadiChanging(value);
                ReportPropertyChanging("Soyadi");
                _Soyadi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Soyadi");
                OnSoyadiChanged();
            }
        }
        private global::System.String _Soyadi;
        partial void OnSoyadiChanging(global::System.String value);
        partial void OnSoyadiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefon
        {
            get
            {
                return _Telefon;
            }
            set
            {
                OnTelefonChanging(value);
                ReportPropertyChanging("Telefon");
                _Telefon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefon");
                OnTelefonChanged();
            }
        }
        private global::System.String _Telefon;
        partial void OnTelefonChanging(global::System.String value);
        partial void OnTelefonChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBTicketSystemModel", "FK_Tbl_Kullanicilar_Tbl_Yetkiler", "Tbl_Yetkiler")]
        public Tbl_Yetkiler Tbl_Yetkiler
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tbl_Yetkiler>("DBTicketSystemModel.FK_Tbl_Kullanicilar_Tbl_Yetkiler", "Tbl_Yetkiler").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tbl_Yetkiler>("DBTicketSystemModel.FK_Tbl_Kullanicilar_Tbl_Yetkiler", "Tbl_Yetkiler").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tbl_Yetkiler> Tbl_YetkilerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tbl_Yetkiler>("DBTicketSystemModel.FK_Tbl_Kullanicilar_Tbl_Yetkiler", "Tbl_Yetkiler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tbl_Yetkiler>("DBTicketSystemModel.FK_Tbl_Kullanicilar_Tbl_Yetkiler", "Tbl_Yetkiler", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBTicketSystemModel", "FK_Tbl_Sikayetler_Tbl_Kullanicilar", "Tbl_Sikayetler")]
        public EntityCollection<Tbl_Sikayetler> Tbl_Sikayetler
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tbl_Sikayetler>("DBTicketSystemModel.FK_Tbl_Sikayetler_Tbl_Kullanicilar", "Tbl_Sikayetler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tbl_Sikayetler>("DBTicketSystemModel.FK_Tbl_Sikayetler_Tbl_Kullanicilar", "Tbl_Sikayetler", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBTicketSystemModel", Name="Tbl_Onaylar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tbl_Onaylar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tbl_Onaylar object.
        /// </summary>
        /// <param name="onayID">Initial value of the OnayID property.</param>
        public static Tbl_Onaylar CreateTbl_Onaylar(global::System.Int32 onayID)
        {
            Tbl_Onaylar tbl_Onaylar = new Tbl_Onaylar();
            tbl_Onaylar.OnayID = onayID;
            return tbl_Onaylar;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OnayID
        {
            get
            {
                return _OnayID;
            }
            set
            {
                if (_OnayID != value)
                {
                    OnOnayIDChanging(value);
                    ReportPropertyChanging("OnayID");
                    _OnayID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OnayID");
                    OnOnayIDChanged();
                }
            }
        }
        private global::System.Int32 _OnayID;
        partial void OnOnayIDChanging(global::System.Int32 value);
        partial void OnOnayIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Onay
        {
            get
            {
                return _Onay;
            }
            set
            {
                OnOnayChanging(value);
                ReportPropertyChanging("Onay");
                _Onay = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Onay");
                OnOnayChanged();
            }
        }
        private global::System.String _Onay;
        partial void OnOnayChanging(global::System.String value);
        partial void OnOnayChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBTicketSystemModel", "FK_Tbl_Sikayetler_Tbl_Onaylar", "Tbl_Sikayetler")]
        public EntityCollection<Tbl_Sikayetler> Tbl_Sikayetler
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tbl_Sikayetler>("DBTicketSystemModel.FK_Tbl_Sikayetler_Tbl_Onaylar", "Tbl_Sikayetler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tbl_Sikayetler>("DBTicketSystemModel.FK_Tbl_Sikayetler_Tbl_Onaylar", "Tbl_Sikayetler", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBTicketSystemModel", Name="Tbl_Sikayetler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tbl_Sikayetler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tbl_Sikayetler object.
        /// </summary>
        /// <param name="sikayetID">Initial value of the SikayetID property.</param>
        public static Tbl_Sikayetler CreateTbl_Sikayetler(global::System.Int32 sikayetID)
        {
            Tbl_Sikayetler tbl_Sikayetler = new Tbl_Sikayetler();
            tbl_Sikayetler.SikayetID = sikayetID;
            return tbl_Sikayetler;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SikayetID
        {
            get
            {
                return _SikayetID;
            }
            set
            {
                if (_SikayetID != value)
                {
                    OnSikayetIDChanging(value);
                    ReportPropertyChanging("SikayetID");
                    _SikayetID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SikayetID");
                    OnSikayetIDChanged();
                }
            }
        }
        private global::System.Int32 _SikayetID;
        partial void OnSikayetIDChanging(global::System.Int32 value);
        partial void OnSikayetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KullaniciID
        {
            get
            {
                return _KullaniciID;
            }
            set
            {
                OnKullaniciIDChanging(value);
                ReportPropertyChanging("KullaniciID");
                _KullaniciID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KullaniciID");
                OnKullaniciIDChanged();
            }
        }
        private Nullable<global::System.Int32> _KullaniciID;
        partial void OnKullaniciIDChanging(Nullable<global::System.Int32> value);
        partial void OnKullaniciIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SikayetKonu
        {
            get
            {
                return _SikayetKonu;
            }
            set
            {
                OnSikayetKonuChanging(value);
                ReportPropertyChanging("SikayetKonu");
                _SikayetKonu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SikayetKonu");
                OnSikayetKonuChanged();
            }
        }
        private global::System.String _SikayetKonu;
        partial void OnSikayetKonuChanging(global::System.String value);
        partial void OnSikayetKonuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SikayetMesaj
        {
            get
            {
                return _SikayetMesaj;
            }
            set
            {
                OnSikayetMesajChanging(value);
                ReportPropertyChanging("SikayetMesaj");
                _SikayetMesaj = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SikayetMesaj");
                OnSikayetMesajChanged();
            }
        }
        private global::System.String _SikayetMesaj;
        partial void OnSikayetMesajChanging(global::System.String value);
        partial void OnSikayetMesajChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Tarih
        {
            get
            {
                return _Tarih;
            }
            set
            {
                OnTarihChanging(value);
                ReportPropertyChanging("Tarih");
                _Tarih = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tarih");
                OnTarihChanged();
            }
        }
        private Nullable<global::System.DateTime> _Tarih;
        partial void OnTarihChanging(Nullable<global::System.DateTime> value);
        partial void OnTarihChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Onay
        {
            get
            {
                return _Onay;
            }
            set
            {
                OnOnayChanging(value);
                ReportPropertyChanging("Onay");
                _Onay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Onay");
                OnOnayChanged();
            }
        }
        private Nullable<global::System.Int32> _Onay;
        partial void OnOnayChanging(Nullable<global::System.Int32> value);
        partial void OnOnayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OnayMesaji
        {
            get
            {
                return _OnayMesaji;
            }
            set
            {
                OnOnayMesajiChanging(value);
                ReportPropertyChanging("OnayMesaji");
                _OnayMesaji = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OnayMesaji");
                OnOnayMesajiChanged();
            }
        }
        private global::System.String _OnayMesaji;
        partial void OnOnayMesajiChanging(global::System.String value);
        partial void OnOnayMesajiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBTicketSystemModel", "FK_Tbl_Sikayetler_Tbl_Kullanicilar", "Tbl_Kullanicilar")]
        public Tbl_Kullanicilar Tbl_Kullanicilar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tbl_Kullanicilar>("DBTicketSystemModel.FK_Tbl_Sikayetler_Tbl_Kullanicilar", "Tbl_Kullanicilar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tbl_Kullanicilar>("DBTicketSystemModel.FK_Tbl_Sikayetler_Tbl_Kullanicilar", "Tbl_Kullanicilar").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tbl_Kullanicilar> Tbl_KullanicilarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tbl_Kullanicilar>("DBTicketSystemModel.FK_Tbl_Sikayetler_Tbl_Kullanicilar", "Tbl_Kullanicilar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tbl_Kullanicilar>("DBTicketSystemModel.FK_Tbl_Sikayetler_Tbl_Kullanicilar", "Tbl_Kullanicilar", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBTicketSystemModel", "FK_Tbl_Sikayetler_Tbl_Onaylar", "Tbl_Onaylar")]
        public Tbl_Onaylar Tbl_Onaylar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tbl_Onaylar>("DBTicketSystemModel.FK_Tbl_Sikayetler_Tbl_Onaylar", "Tbl_Onaylar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tbl_Onaylar>("DBTicketSystemModel.FK_Tbl_Sikayetler_Tbl_Onaylar", "Tbl_Onaylar").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tbl_Onaylar> Tbl_OnaylarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tbl_Onaylar>("DBTicketSystemModel.FK_Tbl_Sikayetler_Tbl_Onaylar", "Tbl_Onaylar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tbl_Onaylar>("DBTicketSystemModel.FK_Tbl_Sikayetler_Tbl_Onaylar", "Tbl_Onaylar", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBTicketSystemModel", Name="Tbl_Yetkiler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tbl_Yetkiler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tbl_Yetkiler object.
        /// </summary>
        /// <param name="yetkiKodu">Initial value of the YetkiKodu property.</param>
        public static Tbl_Yetkiler CreateTbl_Yetkiler(global::System.Int32 yetkiKodu)
        {
            Tbl_Yetkiler tbl_Yetkiler = new Tbl_Yetkiler();
            tbl_Yetkiler.YetkiKodu = yetkiKodu;
            return tbl_Yetkiler;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 YetkiKodu
        {
            get
            {
                return _YetkiKodu;
            }
            set
            {
                if (_YetkiKodu != value)
                {
                    OnYetkiKoduChanging(value);
                    ReportPropertyChanging("YetkiKodu");
                    _YetkiKodu = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("YetkiKodu");
                    OnYetkiKoduChanged();
                }
            }
        }
        private global::System.Int32 _YetkiKodu;
        partial void OnYetkiKoduChanging(global::System.Int32 value);
        partial void OnYetkiKoduChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Yetki
        {
            get
            {
                return _Yetki;
            }
            set
            {
                OnYetkiChanging(value);
                ReportPropertyChanging("Yetki");
                _Yetki = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Yetki");
                OnYetkiChanged();
            }
        }
        private global::System.String _Yetki;
        partial void OnYetkiChanging(global::System.String value);
        partial void OnYetkiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBTicketSystemModel", "FK_Tbl_Kullanicilar_Tbl_Yetkiler", "Tbl_Kullanicilar")]
        public EntityCollection<Tbl_Kullanicilar> Tbl_Kullanicilar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tbl_Kullanicilar>("DBTicketSystemModel.FK_Tbl_Kullanicilar_Tbl_Yetkiler", "Tbl_Kullanicilar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tbl_Kullanicilar>("DBTicketSystemModel.FK_Tbl_Kullanicilar_Tbl_Yetkiler", "Tbl_Kullanicilar", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
